export enum ApiServiceNameEnum {
  AUTH = "Auth",
  USERS = "Users",
  COMPANIES = "Companies",
  PRODUCTS = "Products",
  BRANDS = "Brands",
  PRODUCT_CATEGORIES = "ProductCategories",
  PURCHASES = "Purchases",
  SUPPLIERS = "Suppliers",
  ASSETS = "Assets",
  MESSENGER = "Messenger",
  FACEBOOK = "Facebook",
  DICTIONARY = "Dictionary",
  LOGS = "Logs",
  ORDER = "Order",
}
