export enum ApiUrlEnum {
  DICTIONARY_BASE_URL = "https://dictionaryservice.redground-5e8b9eee.germanywestcentral.azurecontainerapps.io/api/v1",
  AUTH_BASE_URL = "https://authservice.redground-5e8b9eee.germanywestcentral.azurecontainerapps.io/api/v1",
  USERS_BASE_URL = "https://userservice.redground-5e8b9eee.germanywestcentral.azurecontainerapps.io/api/v1",
  PRODUCTS_BASE_URL = "https://productservice.redground-5e8b9eee.germanywestcentral.azurecontainerapps.io/api/v1",
  PRODUCTS = "/products",
  BRANDS = "Brands",
  PRODUCT_CATEGORIES = "ProductCategories",
  USERS = "/users",
  COMPANIES = "/companies",
  LOGS = "/logs",
  AUTH = "/auth",
  DICTIONARY = "/dictionary",
  COUNTRIES = "/countries",
  PREFERENCES = "/preferences",
}
