export enum NavUrlEnum {
  DEV = "https://green-glacier-0d48d5603.4.azurestaticapps.net",
  LOCAL = "http://localhost:8000",
  AUTH = "/auth",
  DASHBOARD = "/dashboard",
  ERROR = "/error",
  MESSENGER = "/messenger",
  ORDERS = "/orders",
  PRODUCTS = "/products",
  PRODUCT_BASIC_DATA = "/product-basic-data",
  PRODUCT_GALLERY = "/product-gallery",
  PRODUCT_VARIANTS = "/manage-variants",
  PRODUCT_SIZE_CHART = "/size-chart",
  PRODUCT_ATTRIBUTES = "/attributes",
  PRODUCT_PURCHASE = "/purchase",
  PROFILE = "/profile",
  SETTINGS = "/settings",
  SUPPORT = "/support",
  TRANSMISSIONS = "/transmissions",
  USERS = "/users",
}
