export enum StoreSliceEnum {
  APP = "appSlice",
  DIALOG = "dialogSlice",
  AUTH = "authSlice",
  DASHBOARD = "dashboardSlice",
  PRODUCTS = "productsSlice",
  PRODUCT_BASIC_DATA = "productBasicDataSlice",
  PRODUCT_GALLERY = "productGallery",
  MANAGE_VARIANTS = "manageVariants",
  ATTRIBUTES = "attributesSlice",
  SIZE_CHART = "sizeChartSlice",
  PURCHASE_PRODUCTS = "purchaseProductsSlice",
  INVOICES = "invoicesSlice",
  MARGINS = "marginsSlice",
  SUPPLIER = "supplierSlice",
  PROFILE = "profileSlice",
  SETTINGS = "settingsSlice",
  MESSENGER = "messengerSlice",
  ORDERS = "ordersSlice",
  SUPPORT = "supportSlice",
  TRANSMISSIONS = "transmissionsSlice",
  USERS = "usersSlice",
}
