export enum StoreSliceEnum {
  APP = "appSlice",
  AUTH = "authSlice",
  DASHBOARD = "dashboardSlice",
  PRODUCTS = "productsSlice",
  PRODUCT_BASIC_DATA = "productBasicDataSlice",
  PRODUCT_GALLERY = "productGallery",
  PROFILE = "profileSlice",
  SETTINGS = "settingsSlice",
  MESSENGER = "messengerSlice",
  ORDERS = "ordersSlice",
  SUPPORT = "supportSlice",
  TRANSMISSIONS = "transmissionsSlice",
  USERS = "usersSlice",
}
