import React, { ComponentPropsWithRef } from "react";

import { ISheIcon } from "@/const/interfaces/primitive-components/ISheIcon.ts";
import { ISheTooltip } from "@/const/interfaces/primitive-components/ISheTooltip.ts";
import { ISheToggle } from "@/const/interfaces/primitive-components/ISheToggle.ts";

export interface ISheOption<T> extends ComponentPropsWithRef<"div"> {
  key?: string;
  id?: string;
  className?: string;
  style?: React.CSSProperties;
  toggleClassName?: string;
  toggleStyle?: React.CSSProperties;
  iconClassName?: string;
  iconStyle?: React.CSSProperties;
  colorsClassName?: string;
  colorsStyle?: React.CSSProperties;
  infoClassName?: string;
  infoStyle?: React.CSSProperties;
  tooltipClassName?: string;
  tooltipStyle?: React.CSSProperties;
  minWidth?: string;
  maxWidth?: string;
  fullWidth?: boolean;
  disabled?: boolean;
  isLoading?: boolean;
  ariaDescribedbyId?: string;
  mode?: "single" | "multiple" | "plain";
  view?: "normal" | "card";
  value?: T;
  showIconsColumn?: boolean;
  icon?: Partial<ISheIcon> | string | React.FC<any>;
  iconProps?: ISheIcon;
  showColorsColumn?: boolean;
  colors?: string[];
  text?: string;
  textTransKey?: string;
  description?: string;
  descriptionTransKey?: string;
  sideText?: string;
  sideTextTransKey?: string;
  sideDescription?: string;
  sideDescriptionTransKey?: string;
  isSelected?: boolean;
  tooltip?: ISheTooltip;
  toggleProps?: ISheToggle;
  checkOnClick?: boolean;
  onCheck?(value: T, event?: React.MouseEvent): void;
  onClick?(value: T, event?: React.MouseEvent): void;
}
